"""empty message

Revision ID: 21717de76992
Revises: 88e6ae54e05a
Create Date: 2025-03-29 20:29:30.972197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21717de76992'
down_revision: Union[str, None] = '88e6ae54e05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_keys', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('gcp_keys', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gcp_keys', 'created_at')
    op.drop_column('azure_keys', 'created_at')
    # ### end Alembic commands ###
