"""empty message

Revision ID: 0630acf9e008
Revises: 6ad66ca283b5
Create Date: 2025-04-18 22:10:09.535873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0630acf9e008'
down_revision: Union[str, None] = '6ad66ca283b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcp_remote_backend_config', sa.Column('gcp_project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'gcp_remote_backend_config', 'gcp_keys', ['gcp_project_id'], ['project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gcp_remote_backend_config', type_='foreignkey')
    op.drop_column('gcp_remote_backend_config', 'gcp_project_id')
    # ### end Alembic commands ###
