"""empty message

Revision ID: 08eb869f137b
Revises: d7a9e1a89d58
Create Date: 2025-03-31 14:44:11.702412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08eb869f137b'
down_revision: Union[str, None] = 'd7a9e1a89d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraform_log_file', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraform_log_file', 'provider')
    # ### end Alembic commands ###
