"""empty message

Revision ID: 0e10260ae036
Revises: 0630acf9e008
Create Date: 2025-04-18 22:14:44.643032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e10260ae036'
down_revision: Union[str, None] = '0630acf9e008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcp_keys', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_index('ix_gcp_keys_project_id', table_name='gcp_keys')
    op.create_index(op.f('ix_gcp_keys_project_id'), 'gcp_keys', ['project_id'], unique=True)
    op.add_column('gcp_remote_backend_config', sa.Column('gcp_project_id', sa.String(), nullable=True))
    op.drop_constraint('gcp_remote_backend_config_key_id_fkey', 'gcp_remote_backend_config', type_='foreignkey')
    op.create_foreign_key(None, 'gcp_remote_backend_config', 'gcp_keys', ['gcp_project_id'], ['project_id'])
    op.drop_column('gcp_remote_backend_config', 'key_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcp_remote_backend_config', sa.Column('key_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gcp_remote_backend_config', type_='foreignkey')
    op.create_foreign_key('gcp_remote_backend_config_key_id_fkey', 'gcp_remote_backend_config', 'gcp_keys', ['key_id'], ['id'])
    op.drop_column('gcp_remote_backend_config', 'gcp_project_id')
    op.drop_index(op.f('ix_gcp_keys_project_id'), table_name='gcp_keys')
    op.create_index('ix_gcp_keys_project_id', 'gcp_keys', ['project_id'], unique=False)
    op.drop_column('gcp_keys', 'active')
    # ### end Alembic commands ###
