"""empty message

Revision ID: 243ae8c87d8c
Revises: 08eb869f137b
Create Date: 2025-03-31 20:15:10.938598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243ae8c87d8c'
down_revision: Union[str, None] = '08eb869f137b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azure_remote_backend_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_group_name', sa.String(), nullable=True),
    sa.Column('storage_account_name', sa.String(), nullable=True),
    sa.Column('container_name', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_azure_remote_backend_config_id'), 'azure_remote_backend_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_azure_remote_backend_config_id'), table_name='azure_remote_backend_config')
    op.drop_table('azure_remote_backend_config')
    # ### end Alembic commands ###
