"""empty message

Revision ID: 5552c06660dd
Revises: 81b8c707543f
Create Date: 2025-04-19 21:31:28.416087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5552c06660dd'
down_revision: Union[str, None] = '81b8c707543f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_remote_backend_config', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('azure_remote_backend_config', 'location')
    # ### end Alembic commands ###
