"""empty message

Revision ID: 56944b9d876c
Revises: 1264531da6ae
Create Date: 2025-04-18 13:21:58.757008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56944b9d876c'
down_revision: Union[str, None] = '1264531da6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraform_log_file', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraform_log_file', 'action')
    # ### end Alembic commands ###
