"""empty message

Revision ID: 6ad66ca283b5
Revises: 85a4e4bbfecd
Create Date: 2025-04-18 22:09:34.282504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad66ca283b5'
down_revision: Union[str, None] = '85a4e4bbfecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcp_keys', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('gcp_remote_backend_config_key_id_fkey', 'gcp_remote_backend_config', type_='foreignkey')
    op.drop_column('gcp_remote_backend_config', 'key_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcp_remote_backend_config', sa.Column('key_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gcp_remote_backend_config_key_id_fkey', 'gcp_remote_backend_config', 'gcp_keys', ['key_id'], ['id'])
    op.drop_column('gcp_keys', 'active')
    # ### end Alembic commands ###
