"""empty message

Revision ID: 6fc719dcdf94
Revises: 85a4e4bbfecd
Create Date: 2025-04-21 17:26:40.609183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc719dcdf94'
down_revision: Union[str, None] = '85a4e4bbfecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_keys', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'azure_keys', ['subscription_id'])
    op.add_column('azure_remote_backend_config', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('azure_remote_backend_config', sa.Column('location', sa.String(), nullable=True))
    op.create_foreign_key(None, 'azure_remote_backend_config', 'azure_keys', ['subscription_id'], ['subscription_id'])
    op.add_column('gcp_keys', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_index('ix_gcp_keys_project_id', table_name='gcp_keys')
    op.create_index(op.f('ix_gcp_keys_project_id'), 'gcp_keys', ['project_id'], unique=True)
    op.add_column('gcp_remote_backend_config', sa.Column('gcp_project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'gcp_remote_backend_config', 'gcp_keys', ['gcp_project_id'], ['project_id'])
    op.add_column('terraform_log_file', sa.Column('stream_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraform_log_file', 'stream_status')
    op.drop_constraint(None, 'gcp_remote_backend_config', type_='foreignkey')
    op.drop_column('gcp_remote_backend_config', 'gcp_project_id')
    op.drop_index(op.f('ix_gcp_keys_project_id'), table_name='gcp_keys')
    op.create_index('ix_gcp_keys_project_id', 'gcp_keys', ['project_id'], unique=False)
    op.drop_column('gcp_keys', 'active')
    op.drop_constraint(None, 'azure_remote_backend_config', type_='foreignkey')
    op.drop_column('azure_remote_backend_config', 'location')
    op.drop_column('azure_remote_backend_config', 'subscription_id')
    op.drop_constraint(None, 'azure_keys', type_='unique')
    op.drop_column('azure_keys', 'active')
    # ### end Alembic commands ###
