"""empty message

Revision ID: 81b8c707543f
Revises: c9a25625647a
Create Date: 2025-04-19 18:51:38.450982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b8c707543f'
down_revision: Union[str, None] = 'c9a25625647a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_keys', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('azure_keys', 'active')
    # ### end Alembic commands ###
