"""empty message

Revision ID: 85a4e4bbfecd
Revises: 56944b9d876c
Create Date: 2025-04-18 14:25:51.450727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a4e4bbfecd'
down_revision: Union[str, None] = '56944b9d876c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraform_log_file', sa.Column('cluster_name', sa.String(), nullable=True))
    op.add_column('terraform_log_file', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraform_log_file', 'location')
    op.drop_column('terraform_log_file', 'cluster_name')
    # ### end Alembic commands ###
