"""empty message

Revision ID: c9a25625647a
Revises: 0e10260ae036
Create Date: 2025-04-19 18:12:51.723821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a25625647a'
down_revision: Union[str, None] = '0e10260ae036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'azure_keys', ['subscription_id'])
    op.add_column('azure_remote_backend_config', sa.Column('subscription_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'azure_remote_backend_config', 'azure_keys', ['subscription_id'], ['subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'azure_remote_backend_config', type_='foreignkey')
    op.drop_column('azure_remote_backend_config', 'subscription_id')
    op.drop_constraint(None, 'azure_keys', type_='unique')
    # ### end Alembic commands ###
