"""empty message

Revision ID: d3564dd08939
Revises: 3b3d2cb15ad7
Create Date: 2025-03-31 17:28:29.428654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3564dd08939'
down_revision: Union[str, None] = '3b3d2cb15ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terraform_log_file', sa.Column('stream_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terraform_log_file', 'stream_status')
    # ### end Alembic commands ###
