"""empty message

Revision ID: d7a9e1a89d58
Revises: 3b48001b12be
Create Date: 2025-03-31 14:31:14.938070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a9e1a89d58'
down_revision: Union[str, None] = '3b48001b12be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terraform_log_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'log_id')
    )
    op.create_index(op.f('ix_terraform_log_file_id'), 'terraform_log_file', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terraform_log_file_id'), table_name='terraform_log_file')
    op.drop_table('terraform_log_file')
    # ### end Alembic commands ###
